### ISSUE TITLE
EZproxy and PDFEmbed

### ISSUE THREAD

**Issue by gnosisgithub** [zerocrates/PdfEmbed#2]
I am restricting access to an Omeka install via htaccess and discovered that PDFs are only viewable if:
•             IP is included in the .htacces file that I use to restrict the world from the Omeka
•             The clients hosts file is edited:  146.96.128.35      library.gc.cuny.edu

I think that the issue is either:
•             There is an incompatibility between the JavaScript that is used in the PDF embed plugin and EZproxy. Hence if those two conditions exist the proxy is not being used. I have seen incompatibilities similar to this in the past. For example, SciFinder’s ‘drawing tools’ did not work for almost 6 months because of a similar incompatibility.

•             The fact that we have our server behind a the load balancer and a virtual IP, which might be confusing the client requests.

I am not seeing many error messages, so it is difficult to diagnosis.

The plugin has two settings:
"Object" uses the browser's native PDF viewer or plugins like Adobe Reader. "PDF.js" uses a cross-browser JavaScript-based PDF viewer.

I see this error when I use the Object setting of the plugin:
[Wed Feb 03 09:52:44 2016] [error] [client 146.96.128.15] client denied by server configuration: /var/www/html/legacy/files/original/77864757253e251fef8e19b04ef547e6.pdf, referer: http://myfavesite.ezproxy.edu/legacy/items/show/12130

I see this error in the browser when I use the JS setting of the plugin:
PDF.js v1.0.473 (build: 1694cd8)
Message: Unexpected server response (0) while retrieving PDF "http://myfavesite.edu/legacy/files/original/f2251a58d310d591fece5a22630e0eec.pdf".

**Comment by gnosisgithub** [comment]
The plugin is trying to return:
http://myfakesite.edu/legacy/files/original/f2251a58d310d591fece5a22630e0eec.pdf
rather than:
http://myfavesite.ezproxy.edu/legacy/files/original/f2251a58d310d591fece5a22630e0eec.pdf

and unable to return:
http://myfakesite.edu/legacy/files/original/f2251a58d310d591fece5a22630e0eec.pdf
because .htaccess prevents

Suggest how to append the URL?

**Comment by gnosisgithub** [comment]
Added this:
storage.adapterOptions.webDir = "http://myfavesite.ezproxy.edu/legacy/"

to:
application/config/config.ini

**Comment by zerocrates** [comment]
I'm going to close the issue here as this isn't strictly a PdfEmbed issue, instead having to do with using files behind a proxy more generally.

**Comment by gnosisgithub** [comment]
Thank you, John. Your support was incredible.

On Feb 4, 2016, at 9:36 PM, John Flatness <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #2[github.com]https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zerocrates_PdfEmbed_issues_2&d=CwMCaQ&c=8v77JlHZOYsReeOxyYXDU39VUUzHxyfBUh7fw_ZfBDA&r=RzuvmrjV2OCbxFATfoSTEnF5WFvuPC_o3B3MUQCetc0&m=CLHuPnMTtkXGTFh-_NqM8I83Jnc0Tx3KN-Dm8iDY8yg&s=jdKuATqtOifA824HJ0nnQeJnobYA1ncH-M4KgADGizI&e=.
