### ISSUE TITLE
pdf viewer displaying instead of thumbnails

### ISSUE THREAD

**Issue by adehner** [zerocrates/PdfEmbed#3]
First, this plugin is great. Thanks for creating it.

However, the viewer is displaying instead of thumbnail images on collection/show and solr-search results pages. I believe this is happening because I am looping through the files for each item and grabbing the square thumb for the pdf file. So I'm using file_markup (see below) and the pdf embed viewer is called instead of the thumbnail image.

echo file_markup($file, array('imageSize' => 'square_thumbnail', 'alt' => $itemTitle, 'linkToFile' => false));

How can I only display the pdf viewer in the item/show template, and not in all places where file_markup is called?

Thanks,
Anneliese

**Comment by zerocrates** [comment]
You're going to get the embed whenever you use `file_markup`, as that's the function you're meant to call when you want the "real" rendering of a file (the PDF view, a video or audio player, etc.).

If you instead want to always have images instead, you'd want to use [file_image](http://omeka.readthedocs.io/en/latest/Reference/libraries/globals/file_image.html).

**Comment by adehner** [comment]
Thank you! This fixed it.
